name: grin_mind
description: Grin Mind client
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.0.18
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # This line ensures that the Material Icons font is included.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/